version: "3.8"
services:
  app:
    build: .
    container_name: "${COMPOSE_PROJECT_NAME}-php-app"
    working_dir: /var/www/
    volumes:
      - ./project:/var/www
    networks:
      - app-network
  db:
    image: mysql:5.7
    container_name: "${COMPOSE_PROJECT_NAME}-mysql-db"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123123123"
      MYSQL_DATABASE: "telemeter-db"
      MYSQL_USER: "telemeter"
      MYSQL_PASSWORD: "123123123"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: "${COMPOSE_PROJECT_NAME}-php-nginx"
    ports:
      -  ${COMPOSE_NGINX_PORT}:80
    volumes:
      - ./project:/var/www
      - .docker/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge